Teste_AD_Web/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Teste_AD_Web.Models;

namespace Teste_AD_Web.Controllers
{
    public class ClienteController : Controller
    {
        private readonly ApiContext _context;
        public static Cliente cliGlobal;

        public ClienteController(ApiContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult ListaClientes()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela ListaClientes chamada");
            return View(BuscaClientes("-1"));
        }

        public List<Cliente> BuscaClientes(String id)
        {
            List<Cliente> list = new List<Cliente>();
            var resposta = _context.Clientes.Select(cli => new
            {
                Id = cli.Id,
                nomeCompleto = cli.nomeCompleto,
                cpf = cli.cpf,
                endereco = cli.endereco,
                cep = cli.cep,
                bairro = cli.bairro,
                cidade = cli.cidade,
                uf = cli.uf,
                telefone = cli.telefone
            });
            if (id == "-1") //Pega todos
            {
                foreach (var cli in resposta)
                {
                    Cliente temp = new Cliente();
                    temp.Id = cli.Id;
                    temp.nomeCompleto = cli.nomeCompleto;
                    temp.cpf = cli.cpf;
                    temp.endereco = cli.endereco;
                    temp.cep = cli.cep;
                    temp.bairro = cli.bairro;
                    temp.cidade = cli.cidade;
                    temp.uf = cli.uf;
                    temp.telefone = cli.telefone;
                    list.Add(temp);
                }
            }
            else //Pega o em Questão
            {
                foreach (var p in resposta)
                {
                    if (p.Id.Equals(id))
                    {
                        Cliente temp = new Cliente();
                        temp.Id = p.Id;
                        temp.nomeCompleto = p.nomeCompleto;
                        temp.cpf = p.cpf;
                        temp.endereco = p.endereco;
                        temp.cep = p.cep;
                        temp.bairro = p.bairro;
                        temp.cidade = p.cidade;
                        temp.uf = p.uf;
                        temp.telefone = p.telefone;
                        list.Add(temp);
                        break;
                    }
                }
            }
            return list;
        }

        [HttpGet]
        public IActionResult CadastroClientes()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela CadastroClientes chamada");
            return View();
        }

        [HttpPost]
        public IActionResult CadastroClientes(Cliente cli)
        {
            if (BuscaClientes(cli.Id).Count > 0)
                return View();

            cli.cpf = cli.cpf.Insert(3, ".");
            cli.cpf = cli.cpf.Insert(7, ".");
            cli.cpf = cli.cpf.Insert(11, "-");

            cli.telefone = cli.telefone.Insert(0, "(");
            cli.telefone = cli.telefone.Insert(3, ")");
            cli.telefone = cli.telefone.Insert(4, " ");
            cli.telefone = cli.telefone.Insert(10, "-");

            int nID = 1;
            if (_context.Clientes.Count() > 0)
                nID = Convert.ToInt32(_context.Clientes.Last().Id) + 1;

            var newCli = new Cliente
            {
                Id = Convert.ToString(nID),
                nomeCompleto = cli.nomeCompleto,
                cpf = cli.cpf,
                endereco = cli.endereco,
                cep = cli.cep,
                bairro = cli.bairro,
                cidade = cli.cidade,
                uf = cli.uf.ToUpper(),
                telefone = cli.telefone
            };

            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Cadastro do Novo Cliente(Id=" + newCli.Id + " CPF: " + newCli.cpf + " Nome: " + newCli.nomeCompleto + " Endereco: " + newCli.endereco + " CEP: " + newCli.cep + " Bairro: " + newCli.bairro + " Cidade: " + newCli.cidade + " UF: " + newCli.uf+ " Telefone: " + newCli.telefone+")");
            _context.Clientes.Add(newCli);

            _context.SaveChanges();

            return RedirectToAction("ListaClientes");
        }

        [HttpGet]
        public IActionResult AlteraCliente(Cliente cli)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela AlteraCliente chamada");
            return View(cli);
        }

        [HttpPost]
        public IActionResult AlterarCliente(Cliente cli)
        {
            if (BuscaClientes(cli.Id).Count == 0)
                return View();

            cli.cpf = cli.cpf.Insert(3, ".");
            cli.cpf = cli.cpf.Insert(7, ".");
            cli.cpf = cli.cpf.Insert(11, "-");

            cli.telefone = cli.telefone.Insert(0, "(");
            cli.telefone = cli.telefone.Insert(3, ")");
            cli.telefone = cli.telefone.Insert(4, " ");
            cli.telefone = cli.telefone.Insert(10, "-");

            var newCli = new Cliente
            {
                Id = cli.Id,
                nomeCompleto = cli.nomeCompleto,
                cpf = cli.cpf,
                endereco = cli.endereco,
                cep = cli.cep,
                bairro = cli.bairro,
                cidade = cli.cidade,
                uf = cli.uf.ToUpper(),
                telefone = cli.telefone
            };
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Alterar Cliente(Id=" + cli.Id + " CPF: " + cli.cpf + " Nome: " + cli.nomeCompleto + " Endereco: " + cli.endereco + " CEP: " + cli.cep + " Bairro: " + cli.bairro + " Cidade: " + cli.cidade + " UF: " + cli.uf + " Telefone: " + cli.telefone + ")");
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Alterado para Cliente(Id=" + newCli.Id + " CPF: " + newCli.cpf + " Nome: " + newCli.nomeCompleto + " Endereco: " + newCli.endereco + " CEP: " + newCli.cep + " Bairro: " + newCli.bairro + " Cidade: " + newCli.cidade + " UF: " + newCli.uf + " Telefone: " + newCli.telefone + ")");
            _context.Clientes.Update(newCli);

            _context.SaveChanges();

            return RedirectToAction("ListaClientes");
        }

        [HttpGet]
        public IActionResult DeletaCliente(Cliente c)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela DeletaCliente chamada");
            cliGlobal = c;
            return View(c);
        }
        [HttpPost]
        public IActionResult DeletaCliente()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Deletar Cliente(Id = " + cliGlobal.Id + " CPF: " + cliGlobal.cpf + " Nome: " + cliGlobal.nomeCompleto + " Endereco: " + cliGlobal.endereco + " CEP: " + cliGlobal.cep + " Bairro: " + cliGlobal.bairro + " Cidade: " + cliGlobal.cidade + " UF: " + cliGlobal.uf + " Telefone: " + cliGlobal.telefone + ")");
            _context.Clientes.Remove(cliGlobal);
            _context.SaveChanges();
            return RedirectToAction("ListaClientes");

        }

    }
}

Teste_AD_Web/Controllers/PedidoController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Teste_AD_Web.Models;

namespace Teste_AD_Web.Controllers
{
    public class PedidoController : Controller
    {
        private readonly ApiContext _context;
        public static List<Itens_do_Pedido> listaItensGlobal;
        public static Itens_do_Pedido ItemGlobal;
        public static Pedido pedGlobal;
        public static int tempID;

        public PedidoController(ApiContext context)
        {
            _context = context;
            if (pedGlobal == null)
                pedGlobal = new Pedido();
            if (listaItensGlobal == null)
                listaItensGlobal = new List<Itens_do_Pedido>();
            if (ItemGlobal == null)
                ItemGlobal = new Itens_do_Pedido();


        }
        
        [HttpGet]
        public IActionResult ListaPedidos()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela ListaPedidos chamada");
            pedGlobal = new Pedido();
            listaItensGlobal = new List<Itens_do_Pedido>();
            return View(BuscaPedidos("-1"));
        }

        [HttpGet]
        public IActionResult ListaMeusPedidos()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela ListaMeusPedidos chamada");
            tempID = 1;
            if (_context.Itens_Pedidos.Count() > 0)
                tempID = Convert.ToInt32(_context.Itens_Pedidos.Last().Id) +1;
            pedGlobal = new Pedido();
            listaItensGlobal = new List<Itens_do_Pedido>();

            if (HomeController.cliLogado.Id != null)
                return View(BuscaPedidos(HomeController.cliLogado.Id));
            return RedirectToAction("Login","Home");
        }

        [HttpGet]
        public IActionResult ListaItensPedido(Pedido p)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela ListaItensPedido chamada");
            var itens = BuscaItensPedido(p.Id);
            var prods = BuscaProdutos(itens);
            foreach(var prod in prods)
            {
                ViewData[prod.Id] = prod.categoria + " - " + prod.descricao;
            }
            return View(itens);
        }

        [HttpGet]
        public IActionResult ListaItensMeuPedido(Pedido p)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela ListaItensMeuPedido chamada");
            var itens = BuscaItensPedido(p.Id);
            var prods = BuscaProdutos(itens);
            foreach (var prod in prods)
            {
                ViewData[prod.Id] = prod.categoria + " - " + prod.descricao;
            }
            return View(itens);
        }

        [HttpGet]
        public IActionResult SelecionaItens()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela SelecionaItens chamada");
            ItemGlobal = new Itens_do_Pedido();
            return View(BuscaProdutos(null));
        }
        
        [HttpGet]
        public IActionResult AdicionarItens(Produto prod)//int l1, int l2, int l3)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela AdicionarItens chamada");
            ItemGlobal.Id = Convert.ToString(tempID++);
            ItemGlobal.codProduto = prod.Id;
            ItemGlobal.vlTotal = prod.vlUnitario;

            @ViewData["Produto"] = prod.categoria + " - " + prod.descricao;

            return View(ItemGlobal);
        }

        public IActionResult AdicioneItens(Itens_do_Pedido i)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela AdicioneItens chamada");
            int nID = 1;
            if (_context.Itens_Pedidos.Count() > 0)
                nID = Convert.ToInt32(_context.Itens_Pedidos.Last().Id) + 1;

            ItemGlobal.quantidade = i.quantidade;
            ItemGlobal.vlTotal = ItemGlobal.vlTotal * i.quantidade;
            listaItensGlobal.Add(ItemGlobal);

            return RedirectToAction("SelecionaItens");
        }

        [HttpGet]
        public IActionResult CadastroPedidos()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela CadastroPedidos chamada");
            int nID = 1;
            if (_context.Pedidos.Count() > 0)
                nID = Convert.ToInt32(_context.Pedidos.Last().Id) + 1;


            pedGlobal = new Pedido
            {
                Id = Convert.ToString(nID),
                dtPedido = DateTime.Now,
                cliCodigo = HomeController.cliLogado.Id,
                vlTotal = SomaValorTotalPedido(listaItensGlobal),//pedGlobal.vlTotal,
                vlFrete = CalculaFrete(HomeController.cliLogado.Id),
                IPedido = listaItensGlobal
            };
            
            for (int i=0; i<listaItensGlobal.Count();i++)
            {
                listaItensGlobal[i].PedidoId= pedGlobal.Id;
            }

            var prods = BuscaProdutos(pedGlobal.IPedido);
            foreach (var prod in prods)
            {
                ViewData[prod.Id] = prod.categoria + " - " + prod.descricao;
            }
            if (pedGlobal.IPedido.Count() == 0)
            {
                ViewData["erroItens"] = "Selecione pelo menos um Item para confirmar o Pedido!";
            }
            return View(pedGlobal);
        }

        public IActionResult CadastrarPedidos()
        {
            if(pedGlobal.IPedido.Count()>0)
            {
                pedGlobal.IPedido = null;
                Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Cadastro do Novo Pedido(Id=" + pedGlobal.Id + "dtPedido=" + pedGlobal.dtPedido + "cliCodigo=" + pedGlobal.cliCodigo + "vlTotal=" + pedGlobal.vlTotal + "vlFrete=" + pedGlobal.vlFrete + ")");
                _context.Pedidos.Add(pedGlobal);
                _context.SaveChanges();
                foreach (var i in listaItensGlobal)
                {
                    Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Cadastro do Novo Item de Pedido(Id=" + i.Id + "PedidoId=" + i.PedidoId + "codProduto=" + i.codProduto + "vlTotal=" + i.vlTotal + "quantidade=" + i.quantidade + ")");
                    _context.Itens_Pedidos.Add(i);
                    _context.SaveChanges();
                }
                return RedirectToAction("ListaMeusPedidos"); 
            }
            return RedirectToAction("CadastroPedidos");
        }

        [HttpGet]
        public IActionResult RemoveItem(Itens_do_Pedido i)
        {
            ItemGlobal = i;
            List<Itens_do_Pedido> li = new List<Itens_do_Pedido>();
            li.Add(i);
            var prod = BuscaProdutos(li);
            @ViewData["Produto"] = prod[0].categoria + " - " + prod[0].descricao;

            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela RemoveItem chamada");
            return View(ItemGlobal);
        }

        [HttpPost]
        public IActionResult RemoverItem(Itens_do_Pedido i)
        {
            Itens_do_Pedido aux = BuscaItem(i.Id);
            listaItensGlobal.Remove(aux);

            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Removido o Item(Id=" + aux.Id + "PedidoId=" + aux.PedidoId + "codProduto=" + aux.codProduto + "vlTotal=" + aux.vlTotal + "quantidade=" + aux.quantidade + ")");
            return RedirectToAction("CadastroPedidos");
        }


        [HttpGet]
        public IActionResult DeletaPedido(Pedido Ped)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela DeletaPedido chamada");
            pedGlobal = Ped;
            pedGlobal.IPedido = BuscaItensPedido(pedGlobal.Id);
            var prods = BuscaProdutos(pedGlobal.IPedido);
            foreach (var prod in prods)
            {
                ViewData[prod.Id] = prod.categoria + " - " + prod.descricao;
            }
            return View(pedGlobal);
        }
        [HttpPost]
        public IActionResult DeletarPedido(Pedido Ped)
        {
            _context.Pedidos.Remove(pedGlobal);
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Deletado o Pedido(Id=" + pedGlobal.Id + "dtPedido=" + pedGlobal.dtPedido + "cliCodigo=" + pedGlobal.cliCodigo + "vlTotal=" + pedGlobal.vlTotal + "vlFrete=" + pedGlobal.vlFrete + ")");
            foreach (var i in pedGlobal.IPedido)
            {
                Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Cadastro do Novo Item de Pedido(Id=" + i.Id + "PedidoId=" + i.PedidoId + "codProduto=" + i.codProduto + "vlTotal=" + i.vlTotal + "quantidade=" + i.quantidade + ")");
                _context.Itens_Pedidos.Remove(i);
            }
            _context.SaveChanges();
            return RedirectToAction("ListaMeusPedidos");
        }

        /*
        public void GeraNFE()
        {
            string nome = "";
            var lPedidosCli = BuscaPedidos(HomeController.cliLogado.Id);
            foreach (var p in lPedidosCli)
            {
                nome = "C:\\Users\\1690312\\source\\repos\\Teste_AD_Web\\Teste_AD_Web\\Arquivos Gerados\\Nota Fiscal\\NFe_IdPedido_" + p.Id + "_data_" + DateTime.Now.ToString("dd / MM / yyyy HH: mm: ss") + ".txt";
                StreamWriter sw = File.CreateText(nome);
                sw.Close();
                sw = File.AppendText("========================================");
                sw.WriteLine        ("===========Dados do cliente=============");
                sw.WriteLine("Nome="+HomeController.cliLogado.nomeCompleto + " | CPF=" + HomeController.cliLogado.cpf + " | CEP=" + HomeController.cliLogado.cep);
                sw.Close();
                
                 

Teste_AD_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Teste_AD_Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="background-color:#563d7c;">
            <div class="container">
                <a class="navbar-brand text-light font-weight-bolder" asp-area="" asp-controller="Home" asp-action="Index">Teste_AD_Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-light" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Clientes
                            </button>
                            <div class="dropdown-menu box-shadow" aria-labelledby="dropdownMenuButton" style="background-color: #a998c3;">
                                <a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="ListaClientes">Lista de Clientes</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Cliente" asp-action="CadastroClientes">Cadastrar Cliente</a>
                            </div>
                        </div>

                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-light" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Produtos
                            </button>
                            <div class="dropdown-menu box-shadow" aria-labelledby="dropdownMenuButton" style="background-color: #a998c3;">
                                <a class="dropdown-item" asp-area="" asp-controller="Produto" asp-action="ListaProdutos">Lista de Produtos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Produto" asp-action="CadastroProdutos">Cadastrar Produto</a>
                            </div>
                        </div>
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-light" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Pedidos
                            </button>
                            <div class="dropdown-menu box-shadow" aria-labelledby="dropdownMenuButton" style="background-color: #a998c3;">
                                <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="ListaMeusPedidos">Meus Pedidos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="ListaPedidos">Lista de Todos Pedidos</a>
                                <!--
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="CadastroProdutos">Novo Pedido</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="AlteraProduto">Alterar Pedido</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Pedido" asp-action="DeletaProduto">Deletar Pedido</a>
                                -->
                            </div>
                        </div>
                        <!--
                        <div class="dropdown">
                            <button class="btn dropdown-toggle text-light" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Itens de Pedidos
                            </button>
                            <div class="dropdown-menu box-shadow" aria-labelledby="dropdownMenuButton" style="background-color: #a998c3;">
                                <a class="dropdown-item" asp-area="" asp-controller="Itens_de_Pedidos" asp-action="ListaPedidos">Lista de Itens de Pedidos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Itens_de_Pedidos" asp-action="CadastroProdutos">Cadastrar Itens de Pedidos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Itens_de_Pedidos" asp-action="AlteraProduto">Alterar Itens de Pedidos</a>
                                <a class="dropdown-item" asp-area="" asp-controller="Itens_de_Pedidos" asp-action="DeletaProduto">Deletar Itens de Pedidos</a>
                            </div>
                        </div>
                        -->
                    </ul>
                </div>
            </div>
            <nav class="direita">
                <!--
                <button class="btn text-light" id="btLogin" data-toggle="modal" data-target="#ModalInicio" aria-haspopup="true" aria-expanded="false">
                    Logar
                </button>
                -->

                <a class="btn text-light" asp-area="" asp-controller="Home" asp-action="Login">
                    Logar
                </a>
            </nav>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <!-- Modal Itens-->
    <!--
    <div class="modal fade" id="ModalItens" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header" style="background-color: #a998c3;">
                    <h5 class="modal-title" id="exampleModalLongTitle">Itens do Pedido</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <table style="border-collapse: collapse; width: 100%; text-align: center;">
                        <thead>
                            <tr>
                                <th>
                                    Data
                                </th>
                                <th>
                                    Produto Id
                                </th>
                                <th>
                                    Quantidade
                                </th>
                                <th>
                                    Total
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>
                                    Data
                                </td>
                                <td>
                                    Produto Id
                                </td>
                                <td>
                                    Quantidade
                                </td>
                                <td>
                                    Total
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    Data
                                </td>
                                <td>
                                    Produto Id
                                </td>
                                <td>
                                    Quantidade
                                </td>
                                <td>
                                    Total
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <div class="modal-footer" style="background-color: #a998c3;">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>
        -->
    <!-- FIM MODAL Itens-->

    <!-- Modal Inicio-->
    <!--
    <div class="modal fade" data-backdrop="static" data-keyboard="false" id="ModalInicio" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <form asp-action="Index">
                <div class="modal-content">
                    <div class="modal-header" style="background-color: #a998c3;">
                        <h5 class="modal-title" id="exampleModalLongTitle">Seja Bem-Vindo!</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label asp-for="Id" class="control-label">Entre com seu Id:</label>
                            <input asp-for="Id" class="form-control" />
                        </div>
                    </div>

                    <div class="modal-footer" style="background-color: #a998c3;">
                        <div class="form-group">
                            <input id="btnModalLogin" type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>-->
    <!-- FIM MODAL Inicio-->

    <footer class="border-top footer text-muted" style="background-color:#563d7c;">
        <div class="container" style="color:white;">
            &copy; 2020 - Teste_AD_Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script>
        /*
        var IdCLi = "";
        $(document).ready(function () {
            if (IdCLi == "")
                $('#ModalInicio').modal('show');
        })


        document.getElementById('btnModalLogin').addEventListener('click', function () {
            document.getElementById('btLogin').hidden = true;
        });*/

    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>