Teste_AD_Web/Models/Produto.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Teste_AD_Web.Models
{
    public class Produto
    {
        public string Id { get; set; }
        public string descricao { get; set; }
        public string categoria { get; set; }
        public double vlUnitario { get; set; }
    }
}

Teste_AD_Web/Controllers/ProdutoController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Teste_AD_Web.Models;

namespace Teste_AD_Web.Controllers
{
    //[Produces("application/json")]
    //[Route("api/Produtos")]
    public class ProdutoController : Controller
    {
        private readonly ApiContext _context;
        public static Produto prodGlobal;

        public ProdutoController(ApiContext context)
        {
            _context = context;
        }
        
        [HttpGet]
        public IActionResult ListaProdutos()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela ListaProdutos chamada");
            return View(BuscaProdutos("-1"));
        }
        
        public List<Produto> BuscaProdutos(String id)
        {
            List<Produto> list = new List<Produto>();
            var resposta = _context.Produtos.Select(u => new
            {
                Id = u.Id,
                descricao = u.descricao,
                categoria = u.categoria,
                vlUnitario = u.vlUnitario
            });
            if (id=="-1") //Pega todos produtos
            {
                foreach (var p in resposta)
                {
                    Produto teste = new Produto();
                    teste.Id = p.Id;
                    teste.descricao = p.descricao;
                    teste.categoria = p.categoria;
                    teste.vlUnitario = p.vlUnitario;
                    list.Add(teste);
                }
            }
            else //Pega o em Questão
            {
                foreach (var p in resposta)
                {
                    if(p.Id.Equals(id))
                    {
                        Produto teste = new Produto();
                        teste.Id = p.Id;
                        teste.descricao = p.descricao;
                        teste.categoria = p.categoria;
                        teste.vlUnitario = p.vlUnitario;
                        list.Add(teste);
                        break;
                    }
                }
            }
            return list;
        }

        [HttpGet]
        public IActionResult CadastroProdutos()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela CadastroProdutos chamada");
            return View();
        }

        [HttpPost]
        public IActionResult CadastroProdutos(Produto prod)
        {
            if (BuscaProdutos(prod.Id).Count > 0)
                return View();
            var newProd = new Produto
            {
                Id = prod.Id,
                descricao = prod.descricao,
                categoria = prod.categoria,
                vlUnitario = prod.vlUnitario
            };
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Cadastro do Novo Produto(Id=" + newProd.Id + "descricao="+ newProd.descricao + "categoria=" + newProd.categoria + "vlUnitario=" + newProd.vlUnitario + ")");
            _context.Produtos.Add(newProd);

            _context.SaveChanges();

            return RedirectToAction("ListaProdutos");
        }

        [HttpGet]
        public IActionResult AlteraProduto(Produto prod)
        {
            return View(prod);
        }

        [HttpPost]
        public IActionResult AlterarProduto(Produto prod)
        {
            if (BuscaProdutos(prod.Id).Count == 0)
                return View();
            
            var newProd = new Produto
            {
                Id = prod.Id,
                descricao = prod.descricao,
                categoria = prod.categoria,
                vlUnitario = prod.vlUnitario
            };
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Alterar Produto(Id=" + prod.Id + "descricao=" + prod.descricao + "categoria=" + prod.categoria + "vlUnitario=" + prod.vlUnitario + ")");
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Alterado para Produto(Id=" + newProd.Id + "descricao=" + newProd.descricao + "categoria=" + newProd.categoria + "vlUnitario=" + newProd.vlUnitario + ")");
            _context.Produtos.Update(prod);

            _context.SaveChanges();

            return RedirectToAction("ListaProdutos");
        }

        [HttpGet]
        public IActionResult DeletaProduto(Produto c)
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Tela DeletaCliente chamada");
            prodGlobal = c;
            return View(c);
        }

        [HttpPost]
        public IActionResult DeletaProduto()
        {
            Startup.EscreveNoLog(DateTime.Now.ToString("dd/MM/yyyy HH:mm:ss") + " - Deletar Produto(Id=" + prodGlobal.Id + "descricao=" + prodGlobal.descricao + "categoria=" + prodGlobal.categoria + "vlUnitario=" + prodGlobal.vlUnitario + ")");
            _context.Produtos.Remove(prodGlobal);
            _context.SaveChanges();
            return RedirectToAction("ListaProdutos");
        }
        
    }
}

Teste_AD_Web/Views/Produto/AlteraProduto.cshtml
@model Teste_AD_Web.Models.Produto

@{
    ViewData["Title"] = "Alterar Produto";
}

<h1>Alterar Produto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="AlterarProduto">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label">Id</label>
                <input asp-for="Id" class="form-control" disabled />
                <input asp-for="Id" class="form-control" type="hidden" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descricao" class="control-label">Descrição</label>
                <input asp-for="descricao" class="form-control" minlength="1" />
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoria" class="control-label">Categoria</label>
                <input asp-for="categoria" class="form-control" minlength="1" />
                <span asp-validation-for="categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vlUnitario" class="control-label">Valor Unitário</label>
                <input asp-for="vlUnitario" type="text" class="form-control" />
                <span asp-validation-for="vlUnitario" class="text-danger"></span>
                <span style="color:red">@ViewData["erro"]</span>
            </div>
            <div class="row">
                <input type="submit" value="Salvar" class="btn btn-primary" />

                <div>
                    <a class="btn btn-warning" style="margin-left:12px; width: 120px;" asp-action="ListaProdutos" asp-controller="Produto">Voltar</a>
                </div>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Teste_AD_Web/Views/Produto/CadastroProdutos.cshtml
@model Teste_AD_Web.Models.Produto

@{
    ViewData["Title"] = "CadastroProdutos";
}

<h1>Cadastrar Produto</h1>

<h4>Produto</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CadastroProdutos">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Id" class="control-label">Id</label>
                <input asp-for="Id" class="form-control" minlength="1" required/>
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="descricao" class="control-label">Descrição</label>
                <input asp-for="descricao" class="form-control" minlength="1" required/>
                <span asp-validation-for="descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="categoria" class="control-label">Categoria</label>
                <input asp-for="categoria" class="form-control" minlength="1" required/>
                <span asp-validation-for="categoria" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="vlUnitario" class="control-label">Valor Unitário</label>
                <input asp-for="vlUnitario" class="form-control" required/>
                <span asp-validation-for="vlUnitario" class="text-danger"></span>
            </div>
            <div class="row">
                <input type="submit" value="Salvar" class="btn btn-primary" />

                <div>
                    <a class="btn btn-warning" style="margin-left:12px; width: 120px;" asp-action="ListaProdutos" asp-controller="Produto">Voltar</a>
                </div>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Teste_AD_Web/Views/Produto/DeletaProduto.cshtml
@model Teste_AD_Web.Models.Produto

@{
    ViewData["Title"] = "DeletaProduto";
}

<h1>Deletar Produto</h1>

<h3>Deseja deletar este Produto?</h3>
<div>
    <h4>Produto</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Produto Id
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            Descricao
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.descricao)
        </dd>
        <dt class = "col-sm-2">
            Categoria
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.categoria)
        </dd>
        <dt class = "col-sm-2">
            Valor Unitário
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.vlUnitario)
        </dd>
    </dl>
    
    <form asp-action="DeletaProduto">
        <div class="row">
            <input type="submit" value="Delete" class="btn btn-danger" />

            <div>
                <a class="btn btn-warning" style="margin-left:12px; width: 120px;" asp-action="ListaProdutos" asp-controller="Produto">Voltar</a>
            </div>
        </div>
    </form>
</div>

Teste_AD_Web/Views/Produto/ListaProdutos.cshtml
@model IEnumerable<Teste_AD_Web.Models.Produto>

@{
    ViewData["Title"] = "ListaProdutos";
}

<h1>Lista de Produtos</h1>

<p>
    <a asp-action="CadastroProdutos">Cadastrar Novo</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                Produto Id
            </th>
            <th>
                Descricao
            </th>
            <th>
                Categoria
            </th>
            <th>
                Valor Unitário
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.categoria)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.vlUnitario)
            </td>
            <td>
                @Html.ActionLink("Editar", "AlteraProduto", new { Id = item.Id, descricao = item.descricao, categoria = item.categoria, vlUnitario = item.vlUnitario }) |
                @Html.ActionLink("Delete", "DeletaProduto", new { Id = item.Id, descricao=item.descricao, categoria=item.categoria, vlUnitario=item.vlUnitario })
            </td>
        </tr>
}
    </tbody>
</table>